#server:
#  port: 666
#
#spring:
#  application:
#    name: javaWeb-241011
#
#  datasource:
#    url: jdbc:mysql://8.210.148.116:3306/8bet?useSSL=false
#    username: game
#    password: VJ4X2Buh3N8YEFdHX2v@456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#    hikari:
#      auto-commit: true
#
#  thymeleaf:
#    cache: false
#    enabled: true
#    prefix: classpath:/templates/
#    suffix: .html
#
#  # Logging 設定
#  logging:
#    level:
#      com.zaxxer.hikari: INFO
#      org.springframework.web: DEBUG
#      org.springframework: DEBUG
#
#mybatis:
#  type-aliases-package: com.azhe.pojo
#  configuration:
#    map-underscore-to-camel-case: true
#
## 自定義配置
#azhe:
#  sql:
#    payGenerateLocation: C:\Develop\generateZF-sql\
#
## mybatis mapper 設定 (如果需要)
## mybatis:
##   mapper-locations: classpath:mapper/*.xml
#
## Session 設定 (如果需要)
## server:
##   servlet:
##     session:
##       cookie:
##         name: JJSESSIONID
#
## DevTools 設定 (如果需要)
## spring:
##   devtools:
##     livereload:
##       enabled: true
